# Conexión usando el DNS interno 'db' definido en el compose
spring.datasource.url=jdbc:sqlserver://${DB_HOST:db}:1433;databaseName=BodegaPeiranoDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASSWORD:TuPasswordSeguro123}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Configuración JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Configuración del servidor
server.port=8080